insert into public.projects (
  name,
  tagline,
  status,
  next_milestone,
  mrr,
  mrr_goal,
  mrr_prev,
  launch_date,
  users_count,
  stack,
  url_site,
  category,
  order_index
) values
(
  'OpFanta',
  'Fantacalcio companion app',
  'live',
  'Miglioramenti stagionali e nuove leghe',
  0,
  500,
  0,
  '2024-09-01',
  0,
  array['Next.js', 'Supabase', 'Anthropic API', 'Stripe'],
  'https://opfanta.it',
  'personale',
  1
),
(
  'SCIA-SaaS',
  'Gestione SCIA VVF per tecnici antincendio',
  'building',
  'MVP con gestione pratiche e scadenze',
  0,
  0,
  0,
  null,
  0,
  array['Next.js', 'Supabase', 'Stripe'],
  null,
  'aziendale',
  2
),
(
  'Cost-Assistant',
  'Benchmark costi interni per Perelli Consulting',
  'building',
  'Integrazione dati storici e report mensili',
  0,
  0,
  0,
  null,
  0,
  array['Next.js', 'Supabase', 'Anthropic API'],
  null,
  'aziendale',
  3
);
